name = "TTVFaster"
uuid = "d84f081e-b698-44a3-a477-911041168508"
authors = ["ericagol", "bmlindor"]
version = "0.2.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
